// Generated by scripts/render-thumbnails.mjs. Do not edit by hand.
export const PREVIEW_MANIFEST = {
  "version": "mujljbto",
  "pages": {
    "cv": {
      "classic": 2,
      "profile": 1,
      "grid": 2,
      "crest": 2,
      "editorial": 1,
      "statement": 2,
      "endnote": 2,
      "frame": 2
    },
    "company": {
      "wadani": 3,
      "annual": 3,
      "minimal": 3,
      "standard": 3,
      "dossier": 3,
      "banner": 3,
      "broadsheet": 3,
      "bento": 3
    }
  }
} as const;
